run-tests:
	./gradlew connectedAndroidTest \
	-Pandroid.testInstrumentationRunnerArguments.class=\
	com.example.android.testing.espresso.BasicSample.ui.Tests.HomeScreenUITests
	open app/build/reports/androidTests/connected/debug/com.example.android.testing.espresso.BasicSample.ui.Tests.html